### ISSUE TITLE
AttributeError: 'list' object has no attribute 'size'

### ISSUE THREAD

**Issue by huangs-i2r** [sksq96/pytorch-summary#123]
Encountered this error:

hook_result = hook(self, input, result)
  File "/home/user/pyproject/torchsummary.py", line 31, in hook
    summary[m_key]["input_shape"] = list(input[0].size())
AttributeError: 'list' object has no attribute 'size'

python       3.7.2
torch          1.4.0
torchvision 0.5.0

**Comment by TylerYep** [comment]
Since this project hasn't been worked on in a few months, I decided to do a rewrite of the fixing a lot of the changes.

The changes are available on my fork and is installable using:
pip install torch-summary

No changes to any of your code! It all works the same way but also handles specifying columns and handles LSTMs and RNNs as input.

**Comment by huangs-i2r** [comment]
Thank you.
