### ISSUE TITLE
Do this tool support mutiple inputs? 

### ISSUE THREAD

**Issue by gasvn** [sksq96/pytorch-summary#5]
I tried but failed to print the network information.

**Comment by SunnerLi** [comment]
I think @gasvn advice is great.
This package can be extended in more general case.
In the function of summary, the inputs will be created automatically.
After the inputs are generated, the hook will record the information of each layer.
However, this design idea might limit the generalization.
Maybe ask the user to give the input is another approach.
Because the function just check the information of layer,
the correctness of tensor is not necessary. 
The user can just give the random value.
The following code shows my suggestion:
```python
from torch.autograd import Variable
from model import MyNetwork
import torch.nn as nn
import numpy as np
import torch

b, c, h, w = 32, 1, 28, 28

if __name__ == '__main__':
    input_1 = Variable(torch.from_numpy(np.random.random([b, c, h, w])).float())
    input_2 = Variable(torch.from_numpy(np.random.random([b, c, h, w])).long())
    model = MyNetwork()
    summary(model, input_list = [input_1, input_2])
```

**Comment by sksq96** [comment]
Support for multiple inputs had been added. I have updated [README](https://github.com/sksq96/pytorch-summary#multiple-inputs) for usage.
